name: flet_webview
description: Flet WebView control
homepage: https://flet.dev
repository: https://github.com/DaikyXendo/flet-iap
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0
  in_app_purchase_storekit: ^0.3.21

  flet: ^0.25.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
